queue: example
jobSetId: job-set-1
jobs:
  - namespace: default
    priority: 0
    podSpec:
      priorityClassName: armada-default
      terminationGracePeriodSeconds: 0
      restartPolicy: Never
      containers:
        - name: jenkins-agent-0
          image: jenkins/inbound-agent:latest-jdk21
          command:
            - sh
          args:
            - -c
            - tail -f /dev/null
          resources:
            limits:
              memory: 512Mi
              cpu: 2
            requests:
              memory: 512Mi
              cpu: 2